src/CV-ASP.NET/CV-ASP.NET/Models/CV.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Xml.Serialization;

namespace CV_ASP.NET.Models
{
    public class CV
    {
        [Key]
        public int Cvid {  get; set; } 
        public string? Profilbild { get; set; }

        [Required(ErrorMessage = "Var god ange en beskrivning!")]
        [DisplayName("Beskrivning")]
        public string? Beskrivning { get; set; }

        [NotMapped]
        [DisplayName("Bild")]
        [XmlIgnore]
        public IFormFile? Bildfil { get; set; }
        public string? AnvandarNamn { get; set; }
        public int? AntalBesokare { get; set; } = 0;

        [ForeignKey(nameof(AnvandarNamn))]
        [XmlIgnore]
        public virtual Anvandare? anvandare { get; set; }
        [XmlIgnore]
        public virtual IEnumerable<CV_Utbildning> CvUtbildning { get; set; } = new List<CV_Utbildning>();
        [XmlIgnore]
        public virtual IEnumerable<CV_Erfarenhet> CvErfarenhet { get; set; } = new List<CV_Erfarenhet>();
        [XmlIgnore]
        public virtual IEnumerable<CV_kompetenser> CvKompetenser { get; set; } = new List<CV_kompetenser>();
    }
}

src/CV-ASP.NET/CV-ASP.NET/Models/ViewModels/RedigeraCvViewModel.cs
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;

namespace CV_ASP.NET.Models.ViewModels
{
    public class RedigeraCvViewModel
    {
        
        public string? Profilbild {  get; set; }

        [NotMapped]
        [Required(ErrorMessage = "Du måste lägga in en bild till ditt cv.")]
        public IFormFile? BildFil { get; set; }

        [RegularExpression(@"^[\p{L}\d]*$", ErrorMessage = "Vänligen ange endast bokstäver och siffror i beskrivningen.")]
        [Required(ErrorMessage = "Vänligen skriv en beskrivning av ditt cv.")]
        public string? Beskrivning { get; set; }
    }
}

src/CV-ASP.NET/CV-ASP.NET/Models/ViewModels/SkapaCvViewModel.cs
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel;
using System.Xml.Serialization;

namespace CV_ASP.NET.Models.ViewModels
{
    public class SkapaCvViewModel

    {
        public CV cv {  get; set; }
        public Erfarenhet erfarenhet { get; set; }
        public Kompetenser kompetenser { get; set; }
        public Utbildning utbildning { get; set; }
        public CV_Erfarenhet cvErfarenhet { get; set; }
        public CV_kompetenser cvKompetenser { get; set; }
        public CV_Utbildning cvUtbildning { get; set; } 

        
           
    }
}

src/CV-ASP.NET/CV-ASP.NET/Models/ViewModels/VisaCvViewModel.cs
namespace CV_ASP.NET.Models.ViewModels
{
    public class VisaCvViewModel
    {
        public CV Cv { get; set; }
        public Anvandare anvandare { get; set; }
        public IEnumerable<UtbildningViewModel> utbildningar { get; set; }
        public IEnumerable<ErfarenhetViewModel> erfarenheter { get; set; }
        public IEnumerable<KompetensViewModel> kompetenser { get; set; }
        public IEnumerable<Projekt> projekt { get; set; }
        public string TillAnvandareId { get; set; }

    }

}

src/CV-ASP.NET/CV-ASP.NET/Controllers/CvController.cs
using AspNetCoreGeneratedDocument;
using CV_ASP.NET.DataContext;
using CV_ASP.NET.Models;
using CV_ASP.NET.Models.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Internal;
using System.Diagnostics.CodeAnalysis;
using System.Security.Claims;

namespace CV_ASP.NET.Controllers
{
    public class CvController : BasController
    {
        private TestDataContext testDb;

        private readonly IWebHostEnvironment _webHostEnvironment;
        public CvController(TestDataContext testDb, IWebHostEnvironment webHostEnvironment)
        {
            this.testDb = testDb;
            _webHostEnvironment = webHostEnvironment;
        }

        [HttpPost]
        [Authorize]
        public async Task<IActionResult> TaBortAllaCvn()
        {
            var allaCvn = testDb.CV.ToList();

            testDb.CV.RemoveRange(allaCvn);
            await testDb.SaveChangesAsync();

            return RedirectToAction("Anvsida", "AnvSida");
        }


        public async Task<IActionResult> VisaCv(string anvId)
        {
            return await VisaCvP(anvId);
        }

        // Den här metoden hanterar visning och uppdatering av användarens CV-sida. Om användaren är inloggad, visas den inloggade användarens CV, annars visas den för angiven användare.
        // För externa användare (icke-inloggade) uppdateras besökarantalet för CV:t och relevant information om erfarenheter, kompetenser och utbildningar hämtas och presenteras.
        // Om inga CV finns för användaren, omdirigeras användaren med ett felmeddelande.
        [HttpPost]
        [ActionName("VisaCv")]
        public async Task<IActionResult> VisaCvP(string anvId)
        {
            VisaCvViewModel vm = new VisaCvViewModel { };
            string? inloggadAnv = base.HamtaAnv();



            if
                (anvId == null || anvId.Equals(inloggadAnv))
            {

                vm.anvandare = testDb.Users.Where(a => a.Id.Equals(inloggadAnv)).FirstOrDefault();
                vm.Cv = testDb.CV.Where(c => c.AnvandarNamn.Equals(inloggadAnv)).FirstOrDefault();
            }

            // Om det inte är inloggad användare, uppdatera besökarantalet
            else

            {
                vm.anvandare = testDb.Users.Where(a => a.Id == anvId).FirstOrDefault();
                vm.Cv = testDb.CV.Where(c => c.AnvandarNamn == anvId).FirstOrDefault();

                if (vm.Cv != null)
                {
                    var totalaBesokare = testDb.CV.Where(c => c.Cvid == vm.Cv.Cvid).FirstOrDefault().AntalBesokare;
                    CV cv = vm.Cv;
                    cv.AntalBesokare = totalaBesokare + 1;
                    testDb.Update(cv);
                    await testDb.SaveChangesAsync();
                }

            }

            if (vm.Cv != null)
            {
                vm.erfarenheter = testDb.CV_Erfarenhet
                .Where(ce => ce.Cvid == vm.Cv.Cvid)
                .Join(testDb.Erfarenhet,
                 ce => ce.Eid,
                 e => e.Eid,
                 (ce, e) => new ErfarenhetViewModel
                 {
                     Eid = e.Eid, // Mappa Eid från Erfarenhet till ViewModel
                     Titel = e.Titel,
                     Arbetsgivare = e.Arbetsgivare,
                     Beskrivning = e.Beskrivning,
                     StartDatum = ce.Startdatum,
                     Slutdatum = ce.Slutdatum
                 })
               .ToList();

                vm.kompetenser = testDb.CV_Kompetenser
                 .Where(ce => ce.Cvid == vm.Cv.Cvid)
                .Join(testDb.Kompetenser,
                 ce => ce.Kid,
                k => k.Kid,
                 (ce, k) => new KompetensViewModel
                 {
                     kid = k.Kid,
                     KompetensNamn = ce.KompetensNamn,
                     Beskrivning = k.Beskrivning

                 })
                .ToList();

                vm.utbildningar = testDb.CV_Utbildning
                 .Where(cu => cu.CVid == vm.Cv.Cvid)
                .Join(testDb.Utbildning,
                 cu => cu.Uid,
                u => u.Uid,
                 (cu, u) => new UtbildningViewModel
                 {
                     uid = u.Uid,
                     Instutition = u.Instutition,
                     Kurs_program = u.Kurs_program,
                     Beskrivning = u.Beskrivning,
                     StartDatum = cu.Startdatum,
                     SlutDatum = cu.Slutdatum
                 })
                .ToList();
                try
                {
                    var nuvarandeAnvadare = User.FindFirst(ClaimTypes.NameIdentifier)?.Value;

                    Projekt projekt = testDb.Projekt.Where(p => p.SkapadAv == nuvarandeAnvadare).OrderByDescending(p => p.Pid).First();
                    ViewBag.Projekt = projekt;
                }
                catch (Exception ex)
                {
                    Projekt exp = new Projekt();
                    exp.Namn = "Personen har inte lagt till några projekt";
                }
                try
                {
                    var currentUserId = User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
                    List<Projekt> senasteDeltagandeProjekt = testDb.AnvProjekt
                        .Where(ap => ap.Anvid == currentUserId)
                        .Select(ap => ap.Projekt)
                        .ToList();
                    ViewBag.SenasteDeltagandeProjekt = senasteDeltagandeProjekt;
                }
                catch
                {
                    Projekt exp = new Projekt();
                    exp.Namn = "Personen har inte deltagit i några projekt";
                }

                return View(vm);

            }
            else
            {
                TempData["ErrorMessage"] = "Det finns inget CV för denna person.";

                return RedirectToAction("Index", "Sok");
            }


            return View(vm);
        }

        [Authorize]

        [HttpGet]
        public IActionResult SkapaCv()
        {
            return View();
        }

        // Den här metoden hanterar skapandet av ett nytt CV, inklusive profilbild, erfarenheter, utbildning och kompetenser. 
        // Data valideras och sparas i databasen, och kopplingar skapas mellan olika objekt. 
        // Om allt går bra omdirigeras användaren till sin profilsida, annars visas formuläret igen.
        [Authorize]
        [HttpPost]
        public async Task<IActionResult> skapaCv(SkapaCvViewModel scv)
        {

            if (ModelState.IsValid)
            {
                string fil = LaddaUppProfilbild(scv);
                scv.cv.Profilbild = fil;

                string? inloggadAnv = base.HamtaAnv();
                scv.cv.AnvandarNamn = inloggadAnv;


                var cv = new CV();

                cv.Profilbild = fil;
                cv.Beskrivning = scv.cv.Beskrivning;
                cv.AnvandarNamn = base.HamtaAnv();

                await testDb.AddAsync(cv);
                await testDb.SaveChangesAsync();


                var erfarenhet = new Erfarenhet();

                erfarenhet.Arbetsgivare = scv.erfarenhet.Arbetsgivare;
                erfarenhet.Titel = scv.erfarenhet.Titel;
                erfarenhet.Beskrivning = scv.erfarenhet.Beskrivning;

                await testDb.Erfarenhet.AddAsync(erfarenhet);
                await testDb.SaveChangesAsync();

                int dettaCv = testDb.CV.Where(c => c.AnvandarNamn == inloggadAnv).Single().Cvid;

                var cvErfarenhet = new CV_Erfarenhet();

                cvErfarenhet.Cvid = dettaCv;
                cvErfarenhet.Startdatum = scv.cvErfarenhet.Startdatum;
                cvErfarenhet.Slutdatum = scv.cvErfarenhet.Slutdatum;
                cvErfarenhet.Eid = erfarenhet.Eid;

                await testDb.CV_Erfarenhet.AddAsync(cvErfarenhet);
                await testDb.SaveChangesAsync();


                var utbildning = new Utbildning();


                utbildning.Instutition = scv.utbildning.Instutition;
                utbildning.Beskrivning = scv.utbildning.Beskrivning;
                utbildning.Kurs_program = scv.utbildning.Kurs_program;

                await testDb.Utbildning.AddAsync(utbildning);
                await testDb.SaveChangesAsync();

                var cvUtbildning = new CV_Utbildning();
                cvUtbildning.CVid = dettaCv;
                cvUtbildning.Startdatum = scv.cvUtbildning.Startdatum;
                cvUtbildning.Slutdatum = scv.cvUtbildning.Slutdatum;
                cvUtbildning.Uid = utbildning.Uid;

                await testDb.CV_Utbildning.AddAsync(cvUtbildning);
                await testDb.SaveChangesAsync();


                var kompetenser = new Kompetenser();

                kompetenser.Beskrivning = scv.kompetenser.Beskrivning;


                await testDb.Kompetenser.AddAsync(kompetenser);
                await testDb.SaveChangesAsync();


                var cvKompetens = new CV_kompetenser();
                cvKompetens.Cvid = dettaCv;
                cvKompetens.Kid = kompetenser.Kid;
                cvKompetens.KompetensNamn = scv.cvKompetenser.KompetensNamn;

                await testDb.CV_Kompetenser.AddAsync(cvKompetens);
                await testDb.SaveChangesAsync();

                return RedirectToAction("Anvsida", "AnvSida");
            }
            return View(scv);
        }

        // Den här metoden hanterar uppladdningen av en profilbild för användarens CV. 
        // Filen sparas i en mapp på servern under "Images" och får ett unikt namn baserat på en GUID för att undvika konflikter.
        [Authorize]
        private string LaddaUppProfilbild(SkapaCvViewModel cvm)
        {
            string fileName = null;
            if (cvm.cv.Bildfil != null)
            {

src/CV-ASP.NET/CV-ASP.NET/Views/CV/LaggTillErf.cshtml
@using CV_ASP.NET.Models.ViewModels
@model ErfarenhetViewModel

@{
    ViewData["Title"] = "Lägg till erfarenheter";
}

<div asp-validation-summary="All" class="text-danger"></div>

<form method="post" asp-action="LaggTillErf" enctype="multipart/form-data">
<h3>Erfarenhet</h3>
<div class="form-group row mb-4">
    <label class="col-sm-2">Arbetsgivare:</label>
    <div class="col-sm-4">
        <input asp-for="Arbetsgivare" class="form-control" />
        <span asp-validation-for="Arbetsgivare" class="text-danger"></span>
    </div>
</div>

<div class="form-group row mb-4">
    <label class="col-sm-2">Titel:</label>
    <div class="col-sm-4">
        <input asp-for="Titel" class="form-control" />
        <span asp-validation-for="Titel" class="text-danger"></span>
    </div>
</div>

<div class="form-group row mb-4">
    <label class="col-sm-2">Beskrivning:</label>
    <div class="col-sm-4">
        <textarea asp-for="Beskrivning" class="form-control" rows="5"></textarea>
        <span asp-validation-for="Beskrivning" class="text-danger"></span>
    </div>
</div>

<div class="form-group row mb-4">
    <label class="col-sm-2">Startdatum:</label>
    <div class="col-sm-4">
            <input asp-for="StartDatum" type="date" class="form-control" />
            <span asp-validation-for="StartDatum" class="text-danger"></span>
    </div>
</div>

<div class="form-group row mb-4">
    <label class="col-sm-2">Slutdatum:</label>
    <div class="col-sm-4">
        <input asp-for="Slutdatum" type="date" class="form-control" />
        <span asp-validation-for="Slutdatum" class="text-danger"></span>
    </div>
</div>
    <div class="form-group row">
        <div class="offset-sm-2 col-sm-4">
            <button type="submit" class="btn btn-primary">Lägg till erfarenhet</button>
        </div>
    </div>
</form>

src/CV-ASP.NET/CV-ASP.NET/Views/CV/LaggTillKomp.cshtml
@using CV_ASP.NET.Models.ViewModels
@model KompetensViewModel

@{
    ViewData["Title"] = "Lägg till kompetens";
}

<div asp-validation-summary="All" class="text-danger"></div>

<form method="post" asp-action="LaggTillKomp" enctype="multipart/form-data">
    <h3>Kompetens</h3>
    <div class="form-group row mb-4">
        <label class="col-sm-2">Titel:</label>
        <div class="col-sm-4">
            <input asp-for="KompetensNamn" class="form-control" />
            <span asp-validation-for="KompetensNamn" class="text-danger"></span>
        </div>
    </div>

    <div class="form-group row mb-4">
        <label class="col-sm-2">Beskrivning:</label>
        <div class="col-sm-4">
            <textarea asp-for="Beskrivning" class="form-control" rows="5"></textarea>
            <span asp-validation-for="Beskrivning" class="text-danger"></span>
        </div>
    </div>

    <div class="form-group row">
        <div class="offset-sm-2 col-sm-4">
            <button type="submit" class="btn btn-primary">Lägg till kompetens</button>
        </div>
    </div>
</form>

src/CV-ASP.NET/CV-ASP.NET/Views/CV/LaggTillUtb.cshtml
@using CV_ASP.NET.Models.ViewModels
@model UtbildningViewModel

@{
    ViewData["Title"] = "Lägg till utbildning";
}

<div asp-validation-summary="All" class="text-danger"></div>

<form method="post" asp-action="LaggTillUtb" enctype="multipart/form-data">
    <h3>Utbildning</h3>
    <div class="form-group row mb-4">
        <label class="col-sm-2">Instutition:</label>
        <div class="col-sm-4">
            <input asp-for="Instutition" class="form-control" />
            <span asp-validation-for="Instutition" class="text-danger"></span>
        </div>
    </div>

    <div class="form-group row mb-4">
        <label class="col-sm-2">Kurs/Program:</label>
        <div class="col-sm-4">
            <input asp-for="Kurs_program" class="form-control" />
            <span asp-validation-for="Kurs_program" class="text-danger"></span>
        </div>
    </div>


    <div class="form-group row mb-4">
        <label class="col-sm-2">Beskrivning:</label>
        <div class="col-sm-4">
            <textarea asp-for="Beskrivning" class="form-control" rows="5"></textarea>
            <span asp-validation-for="Beskrivning" class="text-danger"></span>
        </div>
    </div>

    <div class="form-group row mb-4">
        <label class="col-sm-2">Startdatum:</label>
        <div class="col-sm-4">
            <input asp-for="StartDatum" type="date" class="form-control" />
            <span asp-validation-for="StartDatum" class="text-danger"></span>
        </div>
    </div>

    <div class="form-group row mb-4">
        <label class="col-sm-2">Slutdatum:</label>
        <div class="col-sm-4">
            <input asp-for="SlutDatum" type="date" class="form-control" />
            <span asp-validation-for="SlutDatum" class="text-danger"></span>
        </div>
    </div>
    <div class="form-group row">
        <div class="offset-sm-2 col-sm-4">
            <button type="submit" class="btn btn-primary">Lägg till utbildning</button>
        </div>
    </div>
</form>

src/CV-ASP.NET/CV-ASP.NET/Views/CV/RedigeraCv.cshtml
@using CV_ASP.NET.Models.ViewModels
@model RedigeraCvViewModel
<h1>Uppdatera ditt Cv</h1>
<h2>Fyll i Beskrivning och lägg till en bild</h2>

<div asp-validation-summary="All" class="text-danger"></div>

<form method="post" asp-action="RedigeraCv" enctype="multipart/form-data">
    @* Visa nuvarande beskrivning om den finns *@
    @if (!string.IsNullOrEmpty(Model.Beskrivning))
    {
        <div class="form-group row mb-4">
            <label class="col-sm-2">Nuvarande Beskrivning:</label>
            <div class="col-sm-4">
                <p>@Model.Beskrivning</p>
            </div>
        </div>
    }
    <div class="form-group row mb-4">
        <label class="col-sm-2">Ny beskrivning:</label>
        <div class="col-sm-4">
            <textarea asp-for="Beskrivning" class="form-control" rows="5"></textarea>
            <span asp-validation-for="Beskrivning" class="text-danger"></span>
        </div>
    </div>
    @if (!string.IsNullOrEmpty(Model.Profilbild))
    {
        <div class="form-group row mb-4">
            <label class="col-sm-2">Nuvarande Bild:</label>
            <div class="col-sm-4">
                <img src="~/Images/@Model.Profilbild" alt="Profilbild" class="img-thumbnail" style="max-width: 150px;" />
            </div>
        </div>
    }
    <div class="form-group row mb-4">
        <label class="col-sm-2">Ladda upp ny bild:</label>
        <div class="col-sm-4">
            <input type="file" asp-for="BildFil" />
        </div>
    </div>

    <div class="form-group row">
        <div class="offset-sm-2 col-sm-4">
            <button type="submit" class="btn btn-primary">Uppdatera Cv</button>
        </div>
    </div>
</form>

src/CV-ASP.NET/CV-ASP.NET/Views/CV/VisaCv.cshtml
@using CV_ASP.NET.Models.ViewModels
@model VisaCvViewModel
<link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css" rel="stylesheet">
<link rel="stylesheet" href="sites.css">

@{
    ViewData["Title"] = "Visa CV";
}



<div class="anvandar-sida">
    <div class="anvandar-info" style="padding-bottom:60px">
        <p><i class="fas fa-user"></i> <span class="label">Anvandarnamn:</span> @Html.DisplayFor(p => p.anvandare.Anvandarnamn)</p>
        <p><i class="fas fa-user"></i> <span class="label">Förnamn:</span> @Html.DisplayFor(p => p.anvandare.Fornamn)</p>
        <p><i class="fas fa-user"></i> <span class="label">Efternamn:</span> @Html.DisplayFor(p => p.anvandare.Efternamn)</p>
        <p><i class="fas fa-envelope"></i> <span class="label">Epost:</span> @Html.DisplayFor(p => p.anvandare.Email)</p>
        <p><i class="fas fa-city"></i> <span class="label">Stad:</span> @Html.DisplayFor(p => p.anvandare.Stad)</p>
        <p><i class="fas fa-phone"></i> <span class="label">Telefonnummer:</span> @Html.DisplayFor(p => p.anvandare.PhoneNumber)</p>
        <a class="btn btn-dark btn-sm" asp-controller="Meddelande" asp-action="SkickaMeddelande" asp-route-tillAnvandareId="@Model.anvandare.Id">
            Kontakta mig
        </a>


    </div>
    <div class="bild">

        <img src="~/Images/@Html.ValueFor(p => p.Cv.Profilbild)" class="img-fluid" alt="Responsive image" asp-append-version="true" height="200px" width="200px" />
        <p>@Model.Cv.Beskrivning</p>
    </div>
</div>


<div class="cv-container">
    <div class="cv-sida">


        <h1>Erfarenheter, Kompetenser och Utbildningar</h1>

        <h2>Erfarenheter</h2>
        <table class="table">
            <thead>
                <tr>
                    <th>Arbetsgivare</th>
                    <th>Titel</th>
                    <th>Beskrivning</th>
                    <th>Startdatum</th>
                    <th>Slutdatum</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var erfarenheter in Model.erfarenheter)
                {
                    <tr>
                        <td>@erfarenheter.Arbetsgivare</td>
                        <td>@erfarenheter.Titel</td>
                        <td>@erfarenheter.Beskrivning</td>
                        <td>@erfarenheter.StartDatum</td>
                        <td>@erfarenheter.Slutdatum?.ToString("yyyy-MM-dd")</td>
                        <td>
                            @if (Model.anvandare.Anvandarnamn.Equals(User?.Identity?.Name))
                            {

                                <form method="post" asp-controller="Cv" asp-action="TaBortErf" asp-route-id="@erfarenheter.Eid">
                                    <input class="btn btn-dark" type="submit" value="Ta bort" />
                                </form>
                            }
                        </td>
                    </tr>
                }
            </tbody>

        </table>
        @* <form method="post" asp-controller="Cv" asp-action="TaBortErf" asp-route-id="@erfarenhet.erfarenhet.Eid">
            <input class="btn btn-dark" type="submit" value="Ta bort" />
        </form> *@
        <h2>Kompetenser</h2>
        <table class="table">
            <thead>
                <tr>
                    <th>Kompetensnamn</th>
                    <th>Beskrivning</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var kompetens in Model.kompetenser)
                {
                    <tr>
                        <td>@kompetens.KompetensNamn</td>
                        <td>@kompetens.Beskrivning</td>
                        <td>
                            @if (Model.anvandare.Anvandarnamn.Equals(User?.Identity?.Name))
                            {

                                <form method="post" asp-controller="Cv" asp-action="TaBortKomp" asp-route-id="@kompetens.kid">
                                    <input class="btn btn-dark" type="submit" value="Ta bort" />
                                </form>
                            }
                        </td>
                    </tr>
                }
            </tbody>
        </table>

        <h2>Utbildningar</h2>
        <table class="table">
            <thead>
                <tr>
                    <th>Institution</th>
                    <th>Kurs/Program</th>
                    <th>Beskrivning</th>
                    <th>Startdatum</th>
                    <th>Slutdatum</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var utbildning in Model.utbildningar)
                {
                    <tr>
                        <td>@utbildning.Instutition</td>
                        <td>@utbildning.Kurs_program</td>
                        <td>@utbildning.Beskrivning</td>
                        <td>@utbildning.StartDatum?.ToString("yyyy-MM-dd")</td>
                        <td>@utbildning.SlutDatum?.ToString("yyyy-MM-dd")</td>
                        <td>
                            @if (Model.anvandare.Anvandarnamn.Equals(User?.Identity?.Name))
                            {

                                <form method="post" asp-controller="Cv" asp-action="TaBortUtb" asp-route-id="@utbildning.uid">
                                    <input class="btn btn-dark" type="submit" value="Ta bort" />
                                </form>
                            }
                        </td>
                    </tr>
                }
            </tbody>
        </table>
        <h2>Senaste skapade projektet</h2>
        
        @if(ViewBag.Projekt != null)
        {
            <div>
            <h3>@ViewBag.Projekt.Namn</h3>
            <p>@ViewBag.Projekt.Beskrivning</p>
            </div>
        }
        else
        {
            <p>Det finns inga projekt</p>
        }

        <h2>Projekt du är medlem i</h2>
        @if (ViewBag.SenasteDeltagandeProjekt != null && ((List<Projekt>)ViewBag.SenasteDeltagandeProjekt).Any())
        {
            @foreach(var projekt in (List<Projekt>)ViewBag.SenasteDeltagandeProjekt)
            {
                <div>
                        <h3 class="card-title">@projekt.Namn</h3>
                        <p class="card-text">@projekt.Beskrivning</p>
                </div>
            }
        }
        else
        {
            <p>Du har inte deltagit i några projekt ännu.</p>
        }
    </div>
</div>




@if (Model.anvandare.Anvandarnamn.Equals(User?.Identity?.Name))
{
    <div class="d-flex">
        <a class="btn btn-dark me-2" asp-action="RedigeraCv" asp-controller="Cv">Redigera Cv</a>
        <a class="btn btn-dark me-2" asp-action="LaggTillKomp" asp-controller="Cv">Lägg till kompetens</a>
        <a class="btn btn-dark me-2" asp-action="LaggTillErf" asp-controller="Cv">Lägg till erfarenhet</a>
        <a class="btn btn-dark me-2" asp-action="LaggTillUtb" asp-controller="Cv">Lägg till utbildning</a>
        <a class="btn btn-dark me-2" asp-action="SkapaProjekt" asp-controller="Projekt">Skapa nytt projekt</a>
    </div>
    <p>Totalt antal besökare: @Model.Cv.AntalBesokare</p>
}