src/CV-ASP.NET/CV-ASP.NET/Models/LoggaIn.cs
using System.ComponentModel.DataAnnotations;

namespace CV_ASP.NET.Models
{
    public class LoggaIn
    {
        [Required(ErrorMessage = "Du måste ange ett användarnamn")]
        [RegularExpression(@"^[a-zA-Z0-9._-]{3,20}$", ErrorMessage = "Fel format på användarnamnet")]
        public string Anvandarnamn { get; set; }

        [Required(ErrorMessage = "Du måste ange ett lösenord")]
        [DataType(DataType.Password)]
        public string Losenord { get; set; }
    }
}

src/CV-ASP.NET/CV-ASP.NET/Models/ViewModels/LoggaInViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace CV_ASP.NET.Models
{
    public class LoggaInViewModel
    {
        [Required(ErrorMessage = "Du måste ange ett användarnamn")]
        [RegularExpression(@"^[a-zA-Z0-9._-]{3,20}$", ErrorMessage = "Fel format på användarnamnet")]
        public string Anvandarnamn { get; set; }

        [Required(ErrorMessage = "Du måste ange ett lösenord")]
        [DataType(DataType.Password)]
        public string Losenord { get; set; }
        public bool RememberMe { get; set; }
    }
}

src/CV-ASP.NET/CV-ASP.NET/Controllers/LoggInRegistreraController.cs
using CV_ASP.NET.Models;
using CV_ASP.NET.Models.ViewModels;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using CV_ASP.NET.DataContext;

namespace CV_ASP.NET.Controllers
{
    public class LoggInRegistreraController:Controller
    {
        private UserManager<Anvandare> userManager;
        private SignInManager<Anvandare> signInManager;
        private readonly TestDataContext _context;
        public LoggInRegistreraController(UserManager<Anvandare> userMngr,
        SignInManager<Anvandare> signInMngr, TestDataContext context)
        {
            this.userManager = userMngr;
            this.signInManager = signInMngr;
            this._context = context;
        }

        [HttpGet]
        public IActionResult Registrera()
        {
            return View();
        }

        // Hanterar användarregistrering, skapar användare och loggar in vid framgång, annars visas felmeddelanden.
        [HttpPost]
        public async Task<IActionResult> Registrera(RegistreraViewModel registerViewModel)
        {
            if (ModelState.IsValid)
            {
                Anvandare anvandare = new Anvandare()
                {
                    UserName = registerViewModel.Anvandarnamn,
                    Anvandarnamn = registerViewModel.Anvandarnamn,
                    Email = registerViewModel.Email,
                    Efternamn = registerViewModel.Efternamn,
                    Fornamn = registerViewModel.Fornamn,
                    PhoneNumber = registerViewModel.Telefonnummer,
                    PrivatProfil = registerViewModel.PrivatProfil,
                    Gatunamn = registerViewModel.Gatunamn,
                    Stad = registerViewModel.Stad,
                    Postnummer = registerViewModel.Postnummer
                };

                var result = await userManager.CreateAsync(anvandare, registerViewModel.Losenord);

                if (result.Succeeded)
                {
                    await signInManager.SignInAsync(anvandare, isPersistent: true);
                    return RedirectToAction("Index", "Home");
                }
                else
                {
                    foreach (var error in result.Errors)
                    {
                        ModelState.AddModelError("", error.Description);
                    }
                }
            }

            return View(registerViewModel);
        }


        [HttpGet]
        public IActionResult LoggaIn()
        {
            LoggaInViewModel loginViewModel = new LoggaInViewModel();
            return View(loginViewModel);
        }

        // Hanterar användarinloggning, autentiserar med användarnamn och lösenord, och om lyckad inloggning, omdirigerar till startsidan.
        [HttpPost]
        public async Task<IActionResult> LoggaIn(LoggaInViewModel loginViewModel)
        {
            if (ModelState.IsValid)
            {
                var result = await signInManager.PasswordSignInAsync(
                loginViewModel.Anvandarnamn,
                loginViewModel.Losenord,
                isPersistent: loginViewModel.RememberMe,
                lockoutOnFailure: false);
                if (result.Succeeded)
                {
                    return RedirectToAction("Index", "Home");
                }
                else
                {
                    ModelState.AddModelError("", "Fel användarnam/lösenord.");
                }
            }
            return View(loginViewModel);
        }

        [HttpPost]
        public async Task<IActionResult> Logout()
        {
            await signInManager.SignOutAsync();
            return RedirectToAction("Index", "Home");
        }

        }
    }

src/CV-ASP.NET/CV-ASP.NET/Views/LoggInRegistrera/LoggaIn.cshtml
@model LoggaInViewModel
@{
    ViewBag.Titel = "Login";
}
<div class="container">
    <h1> Logga in </h1>

<div asp-validation-summary="All" class="text-danger"></div>
<form method="post" asp-action="LoggaIn">
    <div class="form-group row">
        <div class="col-sm-2">
                <label asp-for="Anvandarnamn"> </label>
        </div>
        <div class="col-sm-4">
            <input asp-for="Anvandarnamn" class="form-control" />
        </div>
    </div>
    <div class="form-group row">
        <div class="col-sm-2">
            <label asp-for="Losenord"></label>
        </div>
        <div class="col-sm-4">
            <input type="password" asp-for="Losenord" class="form-control" />
       <span asp-validation-for="Losenord" class="text-danger"></span>
        </div>
    </div>
    <div class="form-group row">
        <div class="offset-sm-2 col-sm-4">
            <input type="checkbox" asp-for="RememberMe" class="form-check"/>
                <label asp-for="RememberMe"></label>
        </div>
    </div>
    <div class="form-group row">
        <div class="offset-2 col-sm-4">
            <button type="submit" class="btn btn-primary">Login</button>
        </div>
    </div>
    <label>Har du inget konto?</label>
    <a asp-action="Registrera" asp-controller="LoggInRegistrera">Registrera dig</a>
    </form>
</div>

  @section Scripts {
      <partial name ="_ValidationScriptsPartial"/>
  }

src/CV-ASP.NET/CV-ASP.NET/Views/LoggInRegistrera/Registrera.cshtml
@model CV_ASP.NET.Models.ViewModels.RegistreraViewModel

<div class="container">
    <h1>Registrera ny användare</h1>
    <form asp-action="Registrera" method="post" enctype="multipart/form-data">
        @Html.AntiForgeryToken()
        <div>
            <label asp-for="Anvandarnamn">Användarnamn</label>
            <input asp-for="Anvandarnamn" class="form-control" />
            <span asp-validation-for="Anvandarnamn" class="text-danger"></span>
        </div>

        <div>
            <label asp-for="Fornamn">Förnamn</label>
            <input asp-for="Fornamn" class="form-control" />
            <span asp-validation-for="Fornamn" class="text-danger"></span>
        </div>

        <div>
            <label asp-for="Efternamn"></label>
            <input asp-for="Efternamn" class="form-control" />
            <span asp-validation-for="Efternamn" class="text-danger"></span>
        </div>

        <div>
            <label asp-for="Email">Epost</label>
            <input asp-for="Email" class="form-control" />
            <span asp-validation-for="Email" class="text-danger"></span>
        </div> 


        <div>
            <label asp-for="Telefonnummer"></label>
            <input asp-for="Telefonnummer" class="form-control" />
            <span asp-validation-for="Telefonnummer" class="text-danger"></span>
        </div>

        <div>
            <label asp-for="Losenord">Lösenord</label>
            <input asp-for="Losenord" class="form-control" type="password" />
            <span asp-validation-for="Losenord" class="text-danger"></span>
        </div>

        <div>
            <label asp-for="BekraftaLosenord">Bekräfta lösenord</label>
            <input asp-for="BekraftaLosenord" class="form-control" type="password" />
            <span asp-validation-for="BekraftaLosenord" class="text-danger"></span>
        </div>

        <div>
            <label asp-for="PrivatProfil">Vill du ha en privat profil?</label>
            <input asp-for="PrivatProfil" type="checkbox" class="form-check-input" />
        </div>

        <h3>Adressuppgifter</h3>
        <div>
            <label asp-for="Gatunamn"></label>
            <input asp-for="Gatunamn" class="form-control" />
            <span asp-validation-for="Gatunamn" class="text-danger"></span>
        </div>

        <div>
            <label asp-for="Stad"></label>
            <input asp-for="Stad" class="form-control" />
            <span asp-validation-for="Stad" class="text-danger"></span>
        </div>

        <div>
            <label asp-for="Postnummer"></label>
            <input asp-for="Postnummer" class="form-control" />
            <span asp-validation-for="Postnummer" class="text-danger"></span>
        </div>

        <button type="submit" class="btn btn-primary" style="background-color: black; color: white;">Registrera</button>
    </form>
</div>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}